version: "2"
services:
    react_app:
        build:
            dockerfile: Dockerfile
            context: "./react_app"
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - /react_app/node_modules
            - ./react_app:/react_app
        networks:
            - webappnetwork
    express_js:
        build:
            dockerfile: Dockerfile
            context: "./express_js"
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./express_js:/express_js
            - /express_js/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork

networks:
    webappnetwork:
        driver: bridge